export const AUTH_START = "AUTH_START";
export const AUTH_MERCHANT_SUCCESS = "AUTH_MERCHANT_SUCCESS";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL"

export const AUTH_LOGOUT = "AUTH_LOGOUT"; 

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";

export const DELETE_START = "DELETE_START";
export const DELETE_FAIL = "DELETE_FAIL";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const EDIT_START = "EDIT_START";
export const EDIT_FAIL = "EDIT_FAIL";
export const EDIT_SUCCESS = "EDIT_SUCCESS";

export const ADD_START = "ADD_START";
export const ADD_FAIL = "ADD_FAIL";
export const ADD_SUCCESS = "ADD_SUCCESS";

export const BUY_START = "BUY_START";
export const BUY_FAIL = "BUY_FAIL";
export const BUY_SUCCESS = "BUY_SUCCESS";

export const LOAD_CART_START = "LOAD_CART_START";
export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";
export const LOAD_CART_FAIL = "LOAD_CART_FAIL";

export const REMOVE_CARTITEM_START = "REMOVE_CARTITEM_START";
export const REMOVE_CARTITEM_SUCCESS = "REMOVE_CARTITEM_SUCCESS";
export const REMOVE_CARTITEM_FAIL = "REMOVE_CARTITEM_FAIL";

export const ADD_CARTITEM_START = "ADD_CARTITEM_START";
export const ADD_CARTITEM_SUCCESS = "ADD_CARTITEM_SUCCESS";
export const ADD_CARTITEM_FAIL = "ADD_CARTITEM_FAIL";

export const CREATE_START = "CREATE_START";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

export const FLIP_START = "FLIP_START";
export const FLIP_SUCCESS = "FLIP_SUCCESS";
export const FLIP_FAIL = "FLIP_FAIL";

export const FETCH_MERCHANT_DATA_START = "FETCH_MERCHANT_DATA_START";
export const FETCH_MERCHANT_DATA_SUCCESS = "FETCH_MERCHANT_DATA_SUCCESS";
export const FETCH_MERCHANT_DATA_FAIL = "FETCH_MERCHANT_DATA_FAIL";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SET_PASSWORD_START = "SET_PASSWORD_START";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";

export const INIT_FORM = "INIT_FORM";